### ISSUE TITLE
requires utf-8 locale

### ISSUE THREAD

**Issue by unhammer** [sol/doctest#252]
My bitbucket pipeline suddenly started giving

```
doctests: fd:13: hGetLine: end of file
```

on a rerun of a commit that had worked some days earlier. The only difference in the environment that I could see was that the image now had `LC_ALL=C` instead of `LC_ALL=C.UTF-8`. Manually setting `LC_ALL=C.UTF-8` fixed it again. I can reproduce locally. The failure was in a test containing the "§" character:

```
-- >>> parseField (Just "a§b")
```

From what I can tell, the README doesn't mention that a UTF-8 locale is needed. (I also tried wrapping the call to `doctest` in [withUtf8](https://hackage.haskell.org/package/with-utf8-1.0.0.0) but that did not work, only `export LC_ALL=C.UTF-8`.)

However, should any other encoding than UTF-8 be supported? (I came across https://mail.haskell.org/pipermail/haskell-prime/2011-April/thread.html#3395 but it doesn't seem conclusive.)

**Comment by quasicomputational** [comment]
doctest does require UTF-8 already: see https://github.com/sol/doctest/blob/ddef72d3512534533a87f7ca16d25e4d9a80ebed/ghci-wrapper/src/Language/Haskell/GhciWrapper.hs#L70 and nearby code.

I agree that UTF-8 for everything is the way to go. Since you seem to be the first person to have stubbed your toe on this, I suspect that just documenting this state of affairs is a good enough solution.
